### PR TITLE
Add ability to remove respawn of vehicle

### PR DESCRIPTION
**Pull request by Reidond**
So i wanted a functionality of disabling respawn when driver dies. For example when you have external respawning tools.

### CODE REVIEW

**Comment by SceptreOfficial** [comment]
Respawn can already be disabled if set to -1. If I'm following your code right (correct me if I'm wrong), then this is just redundant.

**Comment by Reidond** [comment]
Yeah but i forgot to mention that vehicle deletes after crew death, this PR removes that

**Comment by SceptreOfficial** [comment]
The 'entity'/namespace is deleted. The actual vehicle can remain if the CBA setting is set. What are you trying to accomplish?

**Comment by Reidond** [comment]
Shit i misread `_entity` as `_vehicle` 😅. Gotta need another sleep!

**Pull request closed without merging**
